#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TallerdeReparacion")]
	public partial class DCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserteArticulo(eArticulo instance);
    partial void UpdateeArticulo(eArticulo instance);
    partial void DeleteeArticulo(eArticulo instance);
    partial void InserteUsuario(eUsuario instance);
    partial void UpdateeUsuario(eUsuario instance);
    partial void DeleteeUsuario(eUsuario instance);
    partial void InserteCliente(eCliente instance);
    partial void UpdateeCliente(eCliente instance);
    partial void DeleteeCliente(eCliente instance);
    partial void InserteEntrega(eEntrega instance);
    partial void UpdateeEntrega(eEntrega instance);
    partial void DeleteeEntrega(eEntrega instance);
    partial void InserteEquiporep(eEquiporep instance);
    partial void UpdateeEquiporep(eEquiporep instance);
    partial void DeleteeEquiporep(eEquiporep instance);
    partial void InserteReparacion(eReparacion instance);
    partial void UpdateeReparacion(eReparacion instance);
    partial void DeleteeReparacion(eReparacion instance);
    partial void InserteReparador(eReparador instance);
    partial void UpdateeReparador(eReparador instance);
    partial void DeleteeReparador(eReparador instance);
    partial void InserteTipousu(eTipousu instance);
    partial void UpdateeTipousu(eTipousu instance);
    partial void DeleteeTipousu(eTipousu instance);
    #endregion
		
		public DCDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.TallerdeReparacionConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<eArticulo> eArticulos
		{
			get
			{
				return this.GetTable<eArticulo>();
			}
		}
		
		public System.Data.Linq.Table<eUsuario> eUsuarios
		{
			get
			{
				return this.GetTable<eUsuario>();
			}
		}
		
		public System.Data.Linq.Table<eCliente> eClientes
		{
			get
			{
				return this.GetTable<eCliente>();
			}
		}
		
		public System.Data.Linq.Table<eEntrega> eEntregas
		{
			get
			{
				return this.GetTable<eEntrega>();
			}
		}
		
		public System.Data.Linq.Table<eEquiporep> eEquiporeps
		{
			get
			{
				return this.GetTable<eEquiporep>();
			}
		}
		
		public System.Data.Linq.Table<eReparacion> eReparacions
		{
			get
			{
				return this.GetTable<eReparacion>();
			}
		}
		
		public System.Data.Linq.Table<eReparador> eReparadors
		{
			get
			{
				return this.GetTable<eReparador>();
			}
		}
		
		public System.Data.Linq.Table<eTipousu> eTipousus
		{
			get
			{
				return this.GetTable<eTipousu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Articulo")]
	public partial class eArticulo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idart;
		
		private string _nombre;
		
		private string _desc;
		
		private int _cant;
		
		private EntitySet<eReparacion> _eReparacions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidartChanging(int value);
    partial void OnidartChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescChanging(string value);
    partial void OndescChanged();
    partial void OncantChanging(int value);
    partial void OncantChanged();
    #endregion
		
		public eArticulo()
		{
			this._eReparacions = new EntitySet<eReparacion>(new Action<eReparacion>(this.attach_eReparacions), new Action<eReparacion>(this.detach_eReparacions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idart", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idart
		{
			get
			{
				return this._idart;
			}
			set
			{
				if ((this._idart != value))
				{
					this.OnidartChanging(value);
					this.SendPropertyChanging();
					this._idart = value;
					this.SendPropertyChanged("idart");
					this.OnidartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(80)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(800)")]
		public string desc
		{
			get
			{
				return this._desc;
			}
			set
			{
				if ((this._desc != value))
				{
					this.OndescChanging(value);
					this.SendPropertyChanging();
					this._desc = value;
					this.SendPropertyChanged("desc");
					this.OndescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cant", DbType="Int NOT NULL")]
		public int cant
		{
			get
			{
				return this._cant;
			}
			set
			{
				if ((this._cant != value))
				{
					this.OncantChanging(value);
					this.SendPropertyChanging();
					this._cant = value;
					this.SendPropertyChanged("cant");
					this.OncantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Articulo_Reparacion", Storage="_eReparacions", ThisKey="idart", OtherKey="articulo")]
		public EntitySet<eReparacion> eReparacions
		{
			get
			{
				return this._eReparacions;
			}
			set
			{
				this._eReparacions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eReparacions(eReparacion entity)
		{
			this.SendPropertyChanging();
			entity.eArticulo = this;
		}
		
		private void detach_eReparacions(eReparacion entity)
		{
			this.SendPropertyChanging();
			entity.eArticulo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class eUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idusu;
		
		private string _nombre;
		
		private string _apellido;
		
		private int _dni;
		
		private System.DateTime _fecnac;
		
		private string _email;
		
		private int _tipousu;
		
		private int _numtel;
		
		private string _nomusu;
		
		private string _contraseña;
		
		private EntitySet<eReparador> _eReparadors;
		
		private EntityRef<eTipousu> _Tipousu1;
		
		private EntityRef<eTipousu> _eTipousu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidusuChanging(int value);
    partial void OnidusuChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OndniChanging(int value);
    partial void OndniChanged();
    partial void OnfecnacChanging(System.DateTime value);
    partial void OnfecnacChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntipousuChanging(int value);
    partial void OntipousuChanged();
    partial void OnnumtelChanging(int value);
    partial void OnnumtelChanged();
    partial void OnnomusuChanging(string value);
    partial void OnnomusuChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    #endregion
		
		public eUsuario()
		{
			this._eReparadors = new EntitySet<eReparador>(new Action<eReparador>(this.attach_eReparadors), new Action<eReparador>(this.detach_eReparadors));
			this._Tipousu1 = default(EntityRef<eTipousu>);
			this._eTipousu = default(EntityRef<eTipousu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idusu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idusu
		{
			get
			{
				return this._idusu;
			}
			set
			{
				if ((this._idusu != value))
				{
					this.OnidusuChanging(value);
					this.SendPropertyChanging();
					this._idusu = value;
					this.SendPropertyChanged("idusu");
					this.OnidusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(80)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(80)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni", DbType="Int NOT NULL")]
		public int dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				if ((this._dni != value))
				{
					this.OndniChanging(value);
					this.SendPropertyChanging();
					this._dni = value;
					this.SendPropertyChanged("dni");
					this.OndniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecnac", DbType="Date NOT NULL")]
		public System.DateTime fecnac
		{
			get
			{
				return this._fecnac;
			}
			set
			{
				if ((this._fecnac != value))
				{
					this.OnfecnacChanging(value);
					this.SendPropertyChanging();
					this._fecnac = value;
					this.SendPropertyChanged("fecnac");
					this.OnfecnacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(80)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipousu", DbType="Int NOT NULL")]
		public int tipousu
		{
			get
			{
				return this._tipousu;
			}
			set
			{
				if ((this._tipousu != value))
				{
					if ((this._Tipousu1.HasLoadedOrAssignedValue || this._eTipousu.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntipousuChanging(value);
					this.SendPropertyChanging();
					this._tipousu = value;
					this.SendPropertyChanged("tipousu");
					this.OntipousuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numtel", DbType="Int NOT NULL")]
		public int numtel
		{
			get
			{
				return this._numtel;
			}
			set
			{
				if ((this._numtel != value))
				{
					this.OnnumtelChanging(value);
					this.SendPropertyChanging();
					this._numtel = value;
					this.SendPropertyChanged("numtel");
					this.OnnumtelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomusu", DbType="VarChar(100)")]
		public string nomusu
		{
			get
			{
				return this._nomusu;
			}
			set
			{
				if ((this._nomusu != value))
				{
					this.OnnomusuChanging(value);
					this.SendPropertyChanging();
					this._nomusu = value;
					this.SendPropertyChanged("nomusu");
					this.OnnomusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarChar(100)")]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Reparador", Storage="_eReparadors", ThisKey="idusu", OtherKey="fkusuario")]
		public EntitySet<eReparador> eReparadors
		{
			get
			{
				return this._eReparadors;
			}
			set
			{
				this._eReparadors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipousu_Usuario", Storage="_Tipousu1", ThisKey="tipousu", OtherKey="idtiu", IsForeignKey=true)]
		public eTipousu Tipousu1
		{
			get
			{
				return this._Tipousu1.Entity;
			}
			set
			{
				eTipousu previousValue = this._Tipousu1.Entity;
				if (((previousValue != value) 
							|| (this._Tipousu1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipousu1.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Tipousu1.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._tipousu = value.idtiu;
					}
					else
					{
						this._tipousu = default(int);
					}
					this.SendPropertyChanged("Tipousu1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipousu_Usuario1", Storage="_eTipousu", ThisKey="tipousu", OtherKey="idtiu", IsForeignKey=true)]
		public eTipousu eTipousu
		{
			get
			{
				return this._eTipousu.Entity;
			}
			set
			{
				eTipousu previousValue = this._eTipousu.Entity;
				if (((previousValue != value) 
							|| (this._eTipousu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eTipousu.Entity = null;
						previousValue.eUsuarios.Remove(this);
					}
					this._eTipousu.Entity = value;
					if ((value != null))
					{
						value.eUsuarios.Add(this);
						this._tipousu = value.idtiu;
					}
					else
					{
						this._tipousu = default(int);
					}
					this.SendPropertyChanged("eTipousu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eReparadors(eReparador entity)
		{
			this.SendPropertyChanging();
			entity.eUsuario = this;
		}
		
		private void detach_eReparadors(eReparador entity)
		{
			this.SendPropertyChanging();
			entity.eUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class eCliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idcli;
		
		private string _nombre;
		
		private int _telefono;
		
		private EntitySet<eReparacion> _eReparacions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidcliChanging(int value);
    partial void OnidcliChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OntelefonoChanging(int value);
    partial void OntelefonoChanged();
    #endregion
		
		public eCliente()
		{
			this._eReparacions = new EntitySet<eReparacion>(new Action<eReparacion>(this.attach_eReparacions), new Action<eReparacion>(this.detach_eReparacions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcli", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idcli
		{
			get
			{
				return this._idcli;
			}
			set
			{
				if ((this._idcli != value))
				{
					this.OnidcliChanging(value);
					this.SendPropertyChanging();
					this._idcli = value;
					this.SendPropertyChanged("idcli");
					this.OnidcliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(80)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int NOT NULL")]
		public int telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Reparacion", Storage="_eReparacions", ThisKey="idcli", OtherKey="fkcliente")]
		public EntitySet<eReparacion> eReparacions
		{
			get
			{
				return this._eReparacions;
			}
			set
			{
				this._eReparacions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eReparacions(eReparacion entity)
		{
			this.SendPropertyChanging();
			entity.eCliente = this;
		}
		
		private void detach_eReparacions(eReparacion entity)
		{
			this.SendPropertyChanging();
			entity.eCliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entrega")]
	public partial class eEntrega : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ident;
		
		private bool _hecho;
		
		private string _desc;
		
		private System.DateTime _fecent;
		
		private EntitySet<eReparacion> _Reparacions;
		
		private EntitySet<eReparacion> _eReparacions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidentChanging(int value);
    partial void OnidentChanged();
    partial void OnhechoChanging(bool value);
    partial void OnhechoChanged();
    partial void OndescChanging(string value);
    partial void OndescChanged();
    partial void OnfecentChanging(System.DateTime value);
    partial void OnfecentChanged();
    #endregion
		
		public eEntrega()
		{
			this._Reparacions = new EntitySet<eReparacion>(new Action<eReparacion>(this.attach_Reparacions), new Action<eReparacion>(this.detach_Reparacions));
			this._eReparacions = new EntitySet<eReparacion>(new Action<eReparacion>(this.attach_eReparacions), new Action<eReparacion>(this.detach_eReparacions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ident", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ident
		{
			get
			{
				return this._ident;
			}
			set
			{
				if ((this._ident != value))
				{
					this.OnidentChanging(value);
					this.SendPropertyChanging();
					this._ident = value;
					this.SendPropertyChanged("ident");
					this.OnidentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hecho", DbType="Bit NOT NULL")]
		public bool hecho
		{
			get
			{
				return this._hecho;
			}
			set
			{
				if ((this._hecho != value))
				{
					this.OnhechoChanging(value);
					this.SendPropertyChanging();
					this._hecho = value;
					this.SendPropertyChanged("hecho");
					this.OnhechoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(800)")]
		public string desc
		{
			get
			{
				return this._desc;
			}
			set
			{
				if ((this._desc != value))
				{
					this.OndescChanging(value);
					this.SendPropertyChanging();
					this._desc = value;
					this.SendPropertyChanged("desc");
					this.OndescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecent", DbType="Date NOT NULL")]
		public System.DateTime fecent
		{
			get
			{
				return this._fecent;
			}
			set
			{
				if ((this._fecent != value))
				{
					this.OnfecentChanging(value);
					this.SendPropertyChanging();
					this._fecent = value;
					this.SendPropertyChanged("fecent");
					this.OnfecentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Entrega_Reparacion", Storage="_Reparacions", ThisKey="ident", OtherKey="entrega")]
		public EntitySet<eReparacion> Reparacions
		{
			get
			{
				return this._Reparacions;
			}
			set
			{
				this._Reparacions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Entrega_Reparacion1", Storage="_eReparacions", ThisKey="ident", OtherKey="entrega")]
		public EntitySet<eReparacion> eReparacions
		{
			get
			{
				return this._eReparacions;
			}
			set
			{
				this._eReparacions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Reparacions(eReparacion entity)
		{
			this.SendPropertyChanging();
			entity.Entrega1 = this;
		}
		
		private void detach_Reparacions(eReparacion entity)
		{
			this.SendPropertyChanging();
			entity.Entrega1 = null;
		}
		
		private void attach_eReparacions(eReparacion entity)
		{
			this.SendPropertyChanging();
			entity.eEntrega = this;
		}
		
		private void detach_eReparacions(eReparacion entity)
		{
			this.SendPropertyChanging();
			entity.eEntrega = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Equiporep")]
	public partial class eEquiporep : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ideq;
		
		private string _desc;
		
		private string _problema;
		
		private EntitySet<eReparacion> _eReparacions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnideqChanging(int value);
    partial void OnideqChanged();
    partial void OndescChanging(string value);
    partial void OndescChanged();
    partial void OnproblemaChanging(string value);
    partial void OnproblemaChanged();
    #endregion
		
		public eEquiporep()
		{
			this._eReparacions = new EntitySet<eReparacion>(new Action<eReparacion>(this.attach_eReparacions), new Action<eReparacion>(this.detach_eReparacions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ideq", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ideq
		{
			get
			{
				return this._ideq;
			}
			set
			{
				if ((this._ideq != value))
				{
					this.OnideqChanging(value);
					this.SendPropertyChanging();
					this._ideq = value;
					this.SendPropertyChanged("ideq");
					this.OnideqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(800)")]
		public string desc
		{
			get
			{
				return this._desc;
			}
			set
			{
				if ((this._desc != value))
				{
					this.OndescChanging(value);
					this.SendPropertyChanging();
					this._desc = value;
					this.SendPropertyChanged("desc");
					this.OndescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_problema", DbType="VarChar(500)")]
		public string problema
		{
			get
			{
				return this._problema;
			}
			set
			{
				if ((this._problema != value))
				{
					this.OnproblemaChanging(value);
					this.SendPropertyChanging();
					this._problema = value;
					this.SendPropertyChanged("problema");
					this.OnproblemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equiporep_Reparacion", Storage="_eReparacions", ThisKey="ideq", OtherKey="equiporep")]
		public EntitySet<eReparacion> eReparacions
		{
			get
			{
				return this._eReparacions;
			}
			set
			{
				this._eReparacions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eReparacions(eReparacion entity)
		{
			this.SendPropertyChanging();
			entity.eEquiporep = this;
		}
		
		private void detach_eReparacions(eReparacion entity)
		{
			this.SendPropertyChanging();
			entity.eEquiporep = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reparacion")]
	public partial class eReparacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idr;
		
		private System.DateTime _fecini;
		
		private int _entrega;
		
		private int _fkcliente;
		
		private int _equiporep;
		
		private int _reparador;
		
		private int _articulo;
		
		private EntityRef<eArticulo> _eArticulo;
		
		private EntityRef<eEntrega> _Entrega1;
		
		private EntityRef<eEntrega> _eEntrega;
		
		private EntityRef<eEquiporep> _eEquiporep;
		
		private EntityRef<eCliente> _eCliente;
		
		private EntityRef<eReparador> _eReparador;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidrChanging(int value);
    partial void OnidrChanged();
    partial void OnfeciniChanging(System.DateTime value);
    partial void OnfeciniChanged();
    partial void OnentregaChanging(int value);
    partial void OnentregaChanged();
    partial void OnfkclienteChanging(int value);
    partial void OnfkclienteChanged();
    partial void OnequiporepChanging(int value);
    partial void OnequiporepChanged();
    partial void OnreparadorChanging(int value);
    partial void OnreparadorChanged();
    partial void OnarticuloChanging(int value);
    partial void OnarticuloChanged();
    #endregion
		
		public eReparacion()
		{
			this._eArticulo = default(EntityRef<eArticulo>);
			this._Entrega1 = default(EntityRef<eEntrega>);
			this._eEntrega = default(EntityRef<eEntrega>);
			this._eEquiporep = default(EntityRef<eEquiporep>);
			this._eCliente = default(EntityRef<eCliente>);
			this._eReparador = default(EntityRef<eReparador>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idr", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idr
		{
			get
			{
				return this._idr;
			}
			set
			{
				if ((this._idr != value))
				{
					this.OnidrChanging(value);
					this.SendPropertyChanging();
					this._idr = value;
					this.SendPropertyChanged("idr");
					this.OnidrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecini", DbType="Date NOT NULL")]
		public System.DateTime fecini
		{
			get
			{
				return this._fecini;
			}
			set
			{
				if ((this._fecini != value))
				{
					this.OnfeciniChanging(value);
					this.SendPropertyChanging();
					this._fecini = value;
					this.SendPropertyChanged("fecini");
					this.OnfeciniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entrega", DbType="Int NOT NULL")]
		public int entrega
		{
			get
			{
				return this._entrega;
			}
			set
			{
				if ((this._entrega != value))
				{
					if ((this._Entrega1.HasLoadedOrAssignedValue || this._eEntrega.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnentregaChanging(value);
					this.SendPropertyChanging();
					this._entrega = value;
					this.SendPropertyChanged("entrega");
					this.OnentregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkcliente", DbType="Int NOT NULL")]
		public int fkcliente
		{
			get
			{
				return this._fkcliente;
			}
			set
			{
				if ((this._fkcliente != value))
				{
					if (this._eCliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkclienteChanging(value);
					this.SendPropertyChanging();
					this._fkcliente = value;
					this.SendPropertyChanged("fkcliente");
					this.OnfkclienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equiporep", DbType="Int NOT NULL")]
		public int equiporep
		{
			get
			{
				return this._equiporep;
			}
			set
			{
				if ((this._equiporep != value))
				{
					if (this._eEquiporep.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnequiporepChanging(value);
					this.SendPropertyChanging();
					this._equiporep = value;
					this.SendPropertyChanged("equiporep");
					this.OnequiporepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reparador", DbType="Int NOT NULL")]
		public int reparador
		{
			get
			{
				return this._reparador;
			}
			set
			{
				if ((this._reparador != value))
				{
					if (this._eReparador.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnreparadorChanging(value);
					this.SendPropertyChanging();
					this._reparador = value;
					this.SendPropertyChanged("reparador");
					this.OnreparadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_articulo", DbType="Int NOT NULL")]
		public int articulo
		{
			get
			{
				return this._articulo;
			}
			set
			{
				if ((this._articulo != value))
				{
					if (this._eArticulo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnarticuloChanging(value);
					this.SendPropertyChanging();
					this._articulo = value;
					this.SendPropertyChanged("articulo");
					this.OnarticuloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Articulo_Reparacion", Storage="_eArticulo", ThisKey="articulo", OtherKey="idart", IsForeignKey=true)]
		public eArticulo eArticulo
		{
			get
			{
				return this._eArticulo.Entity;
			}
			set
			{
				eArticulo previousValue = this._eArticulo.Entity;
				if (((previousValue != value) 
							|| (this._eArticulo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eArticulo.Entity = null;
						previousValue.eReparacions.Remove(this);
					}
					this._eArticulo.Entity = value;
					if ((value != null))
					{
						value.eReparacions.Add(this);
						this._articulo = value.idart;
					}
					else
					{
						this._articulo = default(int);
					}
					this.SendPropertyChanged("eArticulo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Entrega_Reparacion", Storage="_Entrega1", ThisKey="entrega", OtherKey="ident", IsForeignKey=true)]
		public eEntrega Entrega1
		{
			get
			{
				return this._Entrega1.Entity;
			}
			set
			{
				eEntrega previousValue = this._Entrega1.Entity;
				if (((previousValue != value) 
							|| (this._Entrega1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Entrega1.Entity = null;
						previousValue.Reparacions.Remove(this);
					}
					this._Entrega1.Entity = value;
					if ((value != null))
					{
						value.Reparacions.Add(this);
						this._entrega = value.ident;
					}
					else
					{
						this._entrega = default(int);
					}
					this.SendPropertyChanged("Entrega1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Entrega_Reparacion1", Storage="_eEntrega", ThisKey="entrega", OtherKey="ident", IsForeignKey=true)]
		public eEntrega eEntrega
		{
			get
			{
				return this._eEntrega.Entity;
			}
			set
			{
				eEntrega previousValue = this._eEntrega.Entity;
				if (((previousValue != value) 
							|| (this._eEntrega.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eEntrega.Entity = null;
						previousValue.eReparacions.Remove(this);
					}
					this._eEntrega.Entity = value;
					if ((value != null))
					{
						value.eReparacions.Add(this);
						this._entrega = value.ident;
					}
					else
					{
						this._entrega = default(int);
					}
					this.SendPropertyChanged("eEntrega");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equiporep_Reparacion", Storage="_eEquiporep", ThisKey="equiporep", OtherKey="ideq", IsForeignKey=true)]
		public eEquiporep eEquiporep
		{
			get
			{
				return this._eEquiporep.Entity;
			}
			set
			{
				eEquiporep previousValue = this._eEquiporep.Entity;
				if (((previousValue != value) 
							|| (this._eEquiporep.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eEquiporep.Entity = null;
						previousValue.eReparacions.Remove(this);
					}
					this._eEquiporep.Entity = value;
					if ((value != null))
					{
						value.eReparacions.Add(this);
						this._equiporep = value.ideq;
					}
					else
					{
						this._equiporep = default(int);
					}
					this.SendPropertyChanged("eEquiporep");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Reparacion", Storage="_eCliente", ThisKey="fkcliente", OtherKey="idcli", IsForeignKey=true)]
		public eCliente eCliente
		{
			get
			{
				return this._eCliente.Entity;
			}
			set
			{
				eCliente previousValue = this._eCliente.Entity;
				if (((previousValue != value) 
							|| (this._eCliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eCliente.Entity = null;
						previousValue.eReparacions.Remove(this);
					}
					this._eCliente.Entity = value;
					if ((value != null))
					{
						value.eReparacions.Add(this);
						this._fkcliente = value.idcli;
					}
					else
					{
						this._fkcliente = default(int);
					}
					this.SendPropertyChanged("eCliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reparador_Reparacion", Storage="_eReparador", ThisKey="reparador", OtherKey="idrep", IsForeignKey=true)]
		public eReparador eReparador
		{
			get
			{
				return this._eReparador.Entity;
			}
			set
			{
				eReparador previousValue = this._eReparador.Entity;
				if (((previousValue != value) 
							|| (this._eReparador.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eReparador.Entity = null;
						previousValue.eReparacions.Remove(this);
					}
					this._eReparador.Entity = value;
					if ((value != null))
					{
						value.eReparacions.Add(this);
						this._reparador = value.idrep;
					}
					else
					{
						this._reparador = default(int);
					}
					this.SendPropertyChanged("eReparador");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reparador")]
	public partial class eReparador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idrep;
		
		private int _cantrep;
		
		private int _cantcliente;
		
		private int _fkusuario;
		
		private EntitySet<eReparacion> _eReparacions;
		
		private EntityRef<eUsuario> _eUsuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidrepChanging(int value);
    partial void OnidrepChanged();
    partial void OncantrepChanging(int value);
    partial void OncantrepChanged();
    partial void OncantclienteChanging(int value);
    partial void OncantclienteChanged();
    partial void OnfkusuarioChanging(int value);
    partial void OnfkusuarioChanged();
    #endregion
		
		public eReparador()
		{
			this._eReparacions = new EntitySet<eReparacion>(new Action<eReparacion>(this.attach_eReparacions), new Action<eReparacion>(this.detach_eReparacions));
			this._eUsuario = default(EntityRef<eUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idrep", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idrep
		{
			get
			{
				return this._idrep;
			}
			set
			{
				if ((this._idrep != value))
				{
					this.OnidrepChanging(value);
					this.SendPropertyChanging();
					this._idrep = value;
					this.SendPropertyChanged("idrep");
					this.OnidrepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantrep", DbType="Int NOT NULL")]
		public int cantrep
		{
			get
			{
				return this._cantrep;
			}
			set
			{
				if ((this._cantrep != value))
				{
					this.OncantrepChanging(value);
					this.SendPropertyChanging();
					this._cantrep = value;
					this.SendPropertyChanged("cantrep");
					this.OncantrepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantcliente", DbType="Int NOT NULL")]
		public int cantcliente
		{
			get
			{
				return this._cantcliente;
			}
			set
			{
				if ((this._cantcliente != value))
				{
					this.OncantclienteChanging(value);
					this.SendPropertyChanging();
					this._cantcliente = value;
					this.SendPropertyChanged("cantcliente");
					this.OncantclienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkusuario", DbType="Int NOT NULL")]
		public int fkusuario
		{
			get
			{
				return this._fkusuario;
			}
			set
			{
				if ((this._fkusuario != value))
				{
					if (this._eUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkusuarioChanging(value);
					this.SendPropertyChanging();
					this._fkusuario = value;
					this.SendPropertyChanged("fkusuario");
					this.OnfkusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reparador_Reparacion", Storage="_eReparacions", ThisKey="idrep", OtherKey="reparador")]
		public EntitySet<eReparacion> eReparacions
		{
			get
			{
				return this._eReparacions;
			}
			set
			{
				this._eReparacions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Reparador", Storage="_eUsuario", ThisKey="fkusuario", OtherKey="idusu", IsForeignKey=true)]
		public eUsuario eUsuario
		{
			get
			{
				return this._eUsuario.Entity;
			}
			set
			{
				eUsuario previousValue = this._eUsuario.Entity;
				if (((previousValue != value) 
							|| (this._eUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eUsuario.Entity = null;
						previousValue.eReparadors.Remove(this);
					}
					this._eUsuario.Entity = value;
					if ((value != null))
					{
						value.eReparadors.Add(this);
						this._fkusuario = value.idusu;
					}
					else
					{
						this._fkusuario = default(int);
					}
					this.SendPropertyChanged("eUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eReparacions(eReparacion entity)
		{
			this.SendPropertyChanging();
			entity.eReparador = this;
		}
		
		private void detach_eReparacions(eReparacion entity)
		{
			this.SendPropertyChanging();
			entity.eReparador = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipousu")]
	public partial class eTipousu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idtiu;
		
		private string _tipodeusu;
		
		private string _desc;
		
		private EntitySet<eUsuario> _Usuarios;
		
		private EntitySet<eUsuario> _eUsuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidtiuChanging(int value);
    partial void OnidtiuChanged();
    partial void OntipodeusuChanging(string value);
    partial void OntipodeusuChanged();
    partial void OndescChanging(string value);
    partial void OndescChanged();
    #endregion
		
		public eTipousu()
		{
			this._Usuarios = new EntitySet<eUsuario>(new Action<eUsuario>(this.attach_Usuarios), new Action<eUsuario>(this.detach_Usuarios));
			this._eUsuarios = new EntitySet<eUsuario>(new Action<eUsuario>(this.attach_eUsuarios), new Action<eUsuario>(this.detach_eUsuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtiu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idtiu
		{
			get
			{
				return this._idtiu;
			}
			set
			{
				if ((this._idtiu != value))
				{
					this.OnidtiuChanging(value);
					this.SendPropertyChanging();
					this._idtiu = value;
					this.SendPropertyChanged("idtiu");
					this.OnidtiuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipodeusu", DbType="VarChar(50)")]
		public string tipodeusu
		{
			get
			{
				return this._tipodeusu;
			}
			set
			{
				if ((this._tipodeusu != value))
				{
					this.OntipodeusuChanging(value);
					this.SendPropertyChanging();
					this._tipodeusu = value;
					this.SendPropertyChanged("tipodeusu");
					this.OntipodeusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(800)")]
		public string desc
		{
			get
			{
				return this._desc;
			}
			set
			{
				if ((this._desc != value))
				{
					this.OndescChanging(value);
					this.SendPropertyChanging();
					this._desc = value;
					this.SendPropertyChanged("desc");
					this.OndescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipousu_Usuario", Storage="_Usuarios", ThisKey="idtiu", OtherKey="tipousu")]
		public EntitySet<eUsuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipousu_Usuario1", Storage="_eUsuarios", ThisKey="idtiu", OtherKey="tipousu")]
		public EntitySet<eUsuario> eUsuarios
		{
			get
			{
				return this._eUsuarios;
			}
			set
			{
				this._eUsuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(eUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Tipousu1 = this;
		}
		
		private void detach_Usuarios(eUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Tipousu1 = null;
		}
		
		private void attach_eUsuarios(eUsuario entity)
		{
			this.SendPropertyChanging();
			entity.eTipousu = this;
		}
		
		private void detach_eUsuarios(eUsuario entity)
		{
			this.SendPropertyChanging();
			entity.eTipousu = null;
		}
	}
}
#pragma warning restore 1591
